#pragma config(Motor,  port1,           reg,           tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           rf,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           rb,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           lf,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           lb,            tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#include "functions.c"

task main(){

		while(true){
			motor[reg] = vexRT[Ch2];
			motor[rf] = -vexRT[Ch3];

			wait1Msec(5);
		}


			/*
			motor[rf] = 118;
			motor[rb] = 118;
			motor[lf] = 118;
			motor[lb] = 118;
			wait1Msec(65000);
			motor[rf] = 0;
			motor[rb] = 0;
			motor[lf] = 0;
			motor[lb] = 0;
			*/

}
