#pragma config(Motor,  port1,           ssr,           tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           lf,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           lb,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           rf,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rb,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           sr,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           sl,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           in,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           ssl,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          up,            tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#include "functions.c"

task drive(){
	bool initial = true;

	while(true){
		if(bVEXNETActive){

			while(initial == true){
					//sets drive to a regular state
					motor[rf] = -vexRT[Ch3];
					motor[rb] = -vexRT[Ch3];
					motor[lf] = -vexRT[Ch2];
					motor[lb] = -vexRT[Ch2];
					if (vexRT[Btn6U] == 1){
						initial = false;
					}

				}

				while(initial == false){
					//sets the drive to reverse
					motor[rf] = vexRT[Ch2];
					motor[rb] = vexRT[Ch2];
					motor[lf] = vexRT[Ch3];
					motor[lb] = vexRT[Ch3];
					if(vexRT[Btn5U] == 1){
						initial = true;
					}

				}

		//so this loop doesn't hog the cpu
		wait1Msec(10);

		}
	}

}



task launch(){
	bool sd = false;

	while(true){
		if(bVEXNETActive){

			/*
			if(vexRT[Btn8D] == 1){
				motor[sr] = 118;
				motor[sl] = 118;

			}
			if(vexRT[Btn8U] == 1){
				motor[sr] = 0;
				motor[sl] = 0;

			}
			*/
			while(sd == false){
					if(vexRT[Btn8D] == 1){
						motor[sr] = 118;
						motor[sl] = 118;
						while(vexRT[Btn8D] == 1){
							wait1Msec(1);
						}
						sd = true;
					}
				}
				while(sd == true){
					if(vexRT[Btn8D] == 1){
						motor[sr] = 0;
						motor[sl] = 0;
						while(vexRT[Btn8D] == 1){
							wait1Msec(1);
						}
						sd = false;
					}
				}


		//so this loop doesn't hog the cpu
		wait1Msec(10);

		}
	}

}

task main(){

	motor[in] = -70;
	//motor[ssl] = -50;
	//motor[ssr] = -50;

	while(true){
		wait1Msec(10);
	}

}
