#pragma config(Motor,  port1,           ssr,           tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           lf,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           lb,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           rf,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rb,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           sr,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           sl,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           in,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           ssl,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          up,            tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//*THIS IS 241E'S Forked Version*//

/**
 * @file    main.c
 * @brief   This file contains the base for competiton code.
 * @details The three sections include Pre-Auton, Auton, and User
 *          Control.
 *
 * @author		Sean Kelley      sgtkode01@gmail.com
 * @author		Bernard Suwirjo  bsuwirjo@gmail.com
 * @author 		Spencer Couture  spence.couture@gmail.com
 */


#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(120)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

// all functions for competition code
#include "functions.c"



/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Pre-Autonomous
//
/////////////////////////////////////////////////////////////////////////////////////////

/**
 * Period before autonomous when bot cannot move, but minimal code can run
 */
void pre_auton()
{
 bStopTasksBetweenModes = true;
}



/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous
//
/////////////////////////////////////////////////////////////////////////////////////////

/**
 * Period of match when bot is using only code to operate.
 */

task autonomous(){

	motor[sr] = 118;
	motor[sl] = 118;
	wait1Msec(1700);

}



/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
/////////////////////////////////////////////////////////////////////////////////////////

/**
 * Period of match when driver controls the bot
 */
task usercontrol(){

	startTask(launch);
	startTask(drive);
	startTask(intake);
	startTask(beep);
	startTask(raise);
	startTask(minilaunch);

	while(true){
		wait1Msec(10);
	}

}
